spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8087
