spring:
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      eureka:
        approximate-zone-from-hostname: true
    gateway:
      routes:
        - id: task-service
          uri:
            http://${TASK_SERVICE_HOST}:8080
          predicates:
            - Path=/v1/tracker/**
          filters:
            - name: AuthenticationFilter

        - id: security-jwt-service
          uri:
            http://${SECURITY_SERVICE_HOST}:8085
          predicates:
            - Path=/v1/auth/**
  application:
    name: api-gateway


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8089